apiVersion: v1
kind: ConfigMap
metadata:
  name: netflix-config
data:
  database.url: "jdbc:postgresql://postgres:5432/netflix_mercados"
  jwt.expiration: "86400000"
  application.properties: |
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    logging.level.root=INFO
    logging.level.com.netflix.mercados=DEBUG
    server.port=8080
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=always
    management.health.livenessState.enabled=true
    management.health.readinessState.enabled=true
