apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-mercados-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.netflix-mercados.com
    secretName: netflix-mercados-tls
  rules:
  - host: api.netflix-mercados.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netflix-mercados-api
            port:
              number: 80
